services:
  - type: web
    name: flemlabs
    runtime: node
    buildCommand: npm install && cd client && npm install --include=dev && npm run build && cd ../server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGO_URI
        sync: false
